export interface TemplateInfo {
  id: number;
  name: string;
  description: string;
  category: string;
  colorScheme: string;
  accentColor: string;
  badgeColor: string;
  imageIndex: number;
  seoKeywords: string[];
  rating: number;
  hasProfile: boolean;
}

export const templates: TemplateInfo[] = [
  {
    id: 1,
    name: "Executive Timeline",
    description: "Navy header with sidebar and timeline layout",
    category: "Executive",
    colorScheme: "from-slate-700 to-slate-900",
    accentColor: "blue",
    badgeColor: "bg-slate-100 text-slate-700 border-slate-300",
    imageIndex: 1,
    seoKeywords: ["creative resume", "designer resume", "portfolio resume", "artistic resume template"],
    rating: 4.3,
    hasProfile: true,
  },
  {
    id: 2,
    name: "Modern Two-Column",
    description: "Slate blue header with photo overlap design",
    category: "Corporate",
    colorScheme: "from-slate-600 to-slate-800",
    accentColor: "blue",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-300",
    imageIndex: 2,
    seoKeywords: ["executive resume", "corporate resume", "manager resume", "business resume template"],
    rating: 4.4,
    hasProfile: true,
  },
  {
    id: 3,
    name: "Creative Director",
    description: "Charcoal header with arched profile photo",
    category: "Creative",
    colorScheme: "from-gray-700 to-gray-900",
    accentColor: "gray",
    badgeColor: "bg-gray-100 text-gray-700 border-gray-300",
    imageIndex: 3,
    seoKeywords: ["tech resume", "developer resume", "programmer resume", "IT resume template"],
    rating: 4.5,
    hasProfile: true,
  },
  {
    id: 4,
    name: "Classic Timeline",
    description: "Clean header with vertical timeline sections",
    category: "Professional",
    colorScheme: "from-slate-600 to-slate-800",
    accentColor: "gray",
    badgeColor: "bg-gray-100 text-gray-700 border-gray-300",
    imageIndex: 4,
    seoKeywords: ["marketing resume", "communications resume", "content creator resume", "advertising resume"],
    rating: 4.6,
    hasProfile: false,
  },
  {
    id: 5,
    name: "Blue Sidebar",
    description: "Bold blue sidebar with skill progress bars",
    category: "Design",
    colorScheme: "from-blue-500 to-blue-700",
    accentColor: "blue",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-300",
    imageIndex: 5,
    seoKeywords: ["sales resume", "business development resume", "account manager resume", "B2B resume"],
    rating: 4.7,
    hasProfile: true,
  },
  {
    id: 6,
    name: "Elegant Single Column",
    description: "Centered purple-accent single column layout",
    category: "Universal",
    colorScheme: "from-purple-500 to-violet-600",
    accentColor: "purple",
    badgeColor: "bg-purple-100 text-purple-700 border-purple-300",
    imageIndex: 6,
    seoKeywords: ["general resume", "universal resume", "all-purpose resume", "professional resume template"],
    rating: 4.8,
    hasProfile: false,
  },
  {
    id: 7,
    name: "Minimalist Modern",
    description: "Modern minimalist for professionals",
    category: "Minimalist",
    colorScheme: "from-gray-600 to-slate-600",
    accentColor: "gray",
    badgeColor: "bg-gray-100 text-gray-700 border-gray-300",
    imageIndex: 1,
    seoKeywords: ["minimalist resume", "clean resume", "modern resume", "simple resume template"],
    rating: 4.9,
    hasProfile: false,
  },
  {
    id: 8,
    name: "Bold Statement",
    description: "Bold design for standout resumes",
    category: "Bold",
    colorScheme: "from-rose-500 to-pink-600",
    accentColor: "rose",
    badgeColor: "bg-rose-100 text-rose-700 border-rose-300",
    imageIndex: 2,
    seoKeywords: ["bold resume", "standout resume", "eye-catching resume", "unique resume template"],
    rating: 4.6,
    hasProfile: true,
  },
  {
    id: 9,
    name: "Classic Traditional",
    description: "Classic format for traditional fields",
    category: "Traditional",
    colorScheme: "from-stone-600 to-neutral-600",
    accentColor: "stone",
    badgeColor: "bg-stone-100 text-stone-700 border-stone-300",
    imageIndex: 3,
    seoKeywords: ["classic resume", "traditional resume", "conservative resume", "formal resume template"],
    rating: 4.7,
    hasProfile: false,
  },
  {
    id: 10,
    name: "Freelance Creative",
    description: "Creative layout for freelancers",
    category: "Freelance",
    colorScheme: "from-violet-500 to-purple-600",
    accentColor: "violet",
    badgeColor: "bg-violet-100 text-violet-700 border-violet-300",
    imageIndex: 4,
    seoKeywords: ["freelance resume", "contractor resume", "self-employed resume", "consultant resume"],
    rating: 4.5,
    hasProfile: true,
  },
  {
    id: 11,
    name: "Executive Leadership",
    description: "Executive style for leadership roles",
    category: "Executive",
    colorScheme: "from-indigo-600 to-blue-700",
    accentColor: "indigo",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-300",
    imageIndex: 5,
    seoKeywords: ["executive resume", "leadership resume", "C-level resume", "senior executive resume"],
    rating: 4.8,
    hasProfile: true,
  },
  {
    id: 12,
    name: "Technical Expert",
    description: "Tech-focused for IT careers",
    category: "Technical",
    colorScheme: "from-indigo-500 to-cyan-500",
    accentColor: "indigo",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-300",
    imageIndex: 6,
    seoKeywords: ["technical resume", "IT expert resume", "software engineer resume", "technical specialist resume"],
    rating: 4.7,
    hasProfile: false,
  },
];

